
export const PUBLISH_RESULT = 'PUBLISH_RESULT';
export const RESET_GAME = 'RESET_GAME';
export const LOAD_PLANET_SUCCESS = 'LOAD_PLANET_SUCCESS';
export const LOAD_VEHICLE_SUCCESS = 'LOAD_VEHICLE_SUCCESS';



